using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.FileIO;

namespace AccessTimeAnalyzerWPF
{
    internal class PrefetchParser
    {
        

        //default contructor
        public PrefetchParser()
        {

        }

        //calls WinPrefetchView.exe to generate a report on the prefetch files on the current system
        public void runPrefetchReportCommand(string reportFileName)
        {
            System.Diagnostics.Process process = new System.Diagnostics.Process();
            System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
            startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
            startInfo.FileName = "cmd.exe";
            const string quote = "\"";
            startInfo.Arguments = "/C WinPrefetchView.exe /scomma " + quote + reportFileName + quote + " /sort " + quote + "Filename" + quote;
            startInfo.Verb = "runas";
            process.StartInfo = startInfo;
            process.Start();
        }

        //reads preftch file generated by WinPrefetchView.exe
        public void readPrefetcCSVFile(string reportFileName, ref List<defaultApp> defaultApps)
        {
            using (TextFieldParser csvParser = new TextFieldParser(reportFileName))
            {
                csvParser.CommentTokens = new string[] { "#" };
                csvParser.SetDelimiters(new string[] { "," });
                csvParser.HasFieldsEnclosedInQuotes = true;

                while (!csvParser.EndOfData)
                {
                    //read line and add each field to a entry in the array
                    string[] fields = csvParser.ReadFields();

                    //check first field to see if the prefetch file is in the defaultApps list
                    //if it is get the fields with the run count and last run dates/times
                    //index 0 = prefetch file name
                    //index 5 = exe location
                    //index 6 = Run count field 
                    //index 7 = last run dates/times
                    //This we want to change to check the app based on the app location instead of prefetch file and get the prefetch file name.
                    foreach (defaultApp app in defaultApps)
                    {
                        if (fields[5].Contains(app.appLocation.Substring(3)))
                        {
                            app.prefetchName = fields[0];
                            app.runCount = fields[6];
                            app.lastRunTime = fields[7];
                        }
                    }

                }
            }

        }

    }
}
